### ISSUE TITLE
Explain idle / reset connections.

### ISSUE THREAD

**Issue by glennpierce** [hjr3/mob#16]
Hi Thanks for the code example.
It is the only solid example of mio that I could find using the new api.

This is probably me being dumb but could maybe explain the code in  the "ready" function of the server
line 121.

I can't quite grasp why connections are reset and made idle. Then at the end of each tick with try to re-register the connection. Could you please elaborate why we do that ?
Where do connections become unregistered ?

Thanks

**Comment by hjr3** [comment]
@glennpierce sure! I was trying to solve https://github.com/hjr3/mob/pull/2 and I talk about this idea of tracking connection state a bit more in http://hermanradtke.com/2015/10/23/managing-connection-state-with-mio-rust.html

This is one strategy for tracking connection state and a few people have pointed out some efficiency issues with it. We have to do something though otherwise we are very likely to re-register a reset connection or miss re-registering an idle connection.

Connections are automatically unregistered because we [register](https://github.com/hjr3/mob/blob/cddf24af036942b84ebbbb9cbc7542f6d9e358f7/src/connection.rs#L252) edge triggered (not level triggered). I talk about the basic triggers in http://hermanradtke.com/2015/07/12/my-basic-understanding-of-mio-and-async-io.html . The tl;dr is that edge-triggered requires us to re-register after we handle the event.

If I did not answer your question, let me know. We can discuss more here or on IRC.

**Comment by glennpierce** [comment]
Thanks. I think that makes sense. The blog post was really useful. 

Does mio not offer something like recv where you can peek at the messag?. That would save having to store a continuation point. Maybe that is not cross platform though.

Would surprise me if the efficiency was noticeable but our perceptions can be off with these things. I guess the first step would be to add bench marking and try to find the penalty incurred by re-registering .

Thanks.
