### ISSUE TITLE
About OneShot PollOpt

### ISSUE THREAD

**Issue by 00imvj00** [hjr3/mob#18]
Hello, first of all, really good example on mio. i have one confusion though. 

1 ) Do we really need to reregister again and again? i think you used PollOpt:: Oneshot, that is why you are reregistering every time. or that is not that case and we need to reregister every time.

2 ) How to read data from soocket to vec![u8; 1024]
     I am able to read data from socket to [u8; 1024] array, but when i try to use vec as variable buffer  to store data on heap, it is not reading from socket to vec. plesae if possible give an example.

3 ) How to track if socket is closed from client side, do we get any notification in MIO ? 

thank you in advance.

**Comment by hjr3** [comment]
> 1 ) Do we really need to reregister again and again? i think you used PollOpt:: Oneshot, that is why you are reregistering every time. or that is not that case and we need to reregister every time.

It is because I am using `OneShot`. I do this to avoid hanging issues. The [`Poll`](https://docs.rs/mio/0.6.9/mio/struct.Poll.html) discusses this a bit.

> 2 ) How to read data from soocket to vec![u8; 1024]
I am able to read data from socket to [u8; 1024] array, but when i try to use vec as variable buffer to store data on heap, it is not reading from socket to vec. plesae if possible give an example.

`vec![u8; 1024]` isn't valid. Do you mean `vec![0; 1024]`? If so, that should work. I know there is an issue when people do `Vec::with_capacity(1024)`. The issue is that the socket is trying to write into the available space. By default, a `Vec` does not allocate the space. Thus, the socket thinks there are 0 bytes left. Make sure that the vector has a length greater than zero and it should work. If you still have trouble, let me know I can try and show a complete example.

> 3 ) How to track if socket is closed from client side, do we get any notification in MIO ?

When the client disconnects you will get a hangup (hup) event.
